/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: false,
  images: {
    domains: ['github.com'],
  },
  env: {
    WS_POLKADOT_CORETIME_CHAIN: process.env.WS_POLKADOT_CORETIME_CHAIN || '',
    WS_KUSAMA_CORETIME_CHAIN: process.env.WS_KUSAMA_CORETIME_CHAIN || '',
    WS_PASEO_CORETIME_CHAIN: process.env.WS_PASEO_CORETIME_CHAIN || '',
    WS_ROCOCO_CORETIME_CHAIN: process.env.WS_ROCOCO_CORETIME_CHAIN || '',
    WS_WESTEND_CORETIME_CHAIN: process.env.WS_WESTEND_CORETIME_CHAIN || '',

    COCOS_INDEXER: process.env.COCOS_INDEXER || '',
    REGIONX_PASEO_INDEXER: process.env.REGIONX_PASEO_INDEXER || '',

    POLKADOT_CORETIME_INDEXER: process.env.POLKADOT_CORETIME_INDEXER || '',
    KUSAMA_CORETIME_INDEXER: process.env.KUSAMA_CORETIME_INDEXER || '',
    PASEO_CORETIME_INDEXER: process.env.PASEO_CORETIME_INDEXER || '',
    WESTEND_CORETIME_INDEXER: process.env.WESTEND_CORETIME_INDEXER || '',
    ROCOCO_CORETIME_INDEXER: process.env.ROCOCO_CORETIME_INDEXER || '',

    POLKADOT_CORETIME_DICT: process.env.POLKADOT_CORETIME_DICT || '',
    KUSAMA_CORETIME_DICT: process.env.KUSAMA_CORETIME_DICT || '',
    PASEO_CORETIME_DICT: process.env.PASEO_CORETIME_DICT || '',
    WESTEND_CORETIME_DICT: process.env.WESTEND_CORETIME_DICT || '',
    ROCOCO_CORETIME_DICT: process.env.ROCOCO_CORETIME_DICT || '',

    WS_REGIONX_COCOS_CHAIN: process.env.WS_REGIONX_COCOS_CHAIN || '',
    WS_REGIONX_PASEO_CHAIN: process.env.WS_REGIONX_PASEO_CHAIN || '',

    WS_POLKADOT_RELAY_CHAIN: process.env.WS_POLKADOT_RELAY_CHAIN,
    WS_KUSAMA_RELAY_CHAIN: process.env.WS_KUSAMA_RELAY_CHAIN,
    WS_PASEO_RELAY_CHAIN: process.env.WS_PASEO_RELAY_CHAIN,
    WS_ROCOCO_RELAY_CHAIN: process.env.WS_ROCOCO_RELAY_CHAIN,
    WS_WESTEND_RELAY_CHAIN: process.env.WS_WESTEND_RELAY_CHAIN,

    EXPERIMENTAL: process.env.EXPERIMENTAL,
  },
};

module.exports = nextConfig;
