export const COREMASK_BIT_LEN = 80;
export const RELAY_CHAIN_BLOCK_TIME = 6 * 1000;
export const SECOND = 1 * 1000;
export const MINUTE = 60 * SECOND;
export const HOUR = 60 * MINUTE;
export const DAY = 24 * HOUR;
export const UNIT_DECIMALS = 10 ** 12;
export const LISTING_DEPOSIT = 0 * UNIT_DECIMALS;
/// Given that a timeslice is 8 minutes;
export const DAY_IN_TIMESLICES = 180;
export const WEEK_IN_TIMESLICES = DAY_IN_TIMESLICES * 7;
